
version: 2

models:
  - name: spending
    description: "Cleaned, aggregated and categorised summation of spending data ingested to date"
    columns:
      - name: narrative
        description: "The primary key for this table"
        tests:
          - not_null

