
version: 2

models:
  - name: stg_spending
    description: "Cleans up the spending.csv originally imported ON 2024-04-07. This file provides the basis for applying categories to later transactions"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_westpac
    description: "Contains all money spent transactions imported after 2024-04-07."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: category
        tests:
          - not_null
          - dbt_utils.not_accepted_values:
              values: ['other', 'OTHER', 'Other']

          